version: 2.1

jobs:
  Build:
    docker:
      - image: python:3.7.3-stretch    
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv ml-api
            . ml-api/bin/activate
            make install
      - save_cache:
          paths:
            - .ml-api
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run lint
          command: |
            . ml-api/bin/activate
            make lint

workflows:
  Build:
    jobs:
      - Build